### ISSUE TITLE
Yeoman Generator

### ISSUE THREAD

**Issue by stevekinney** [turingschool-examples/game-time-starter-kit-FEm1#1]
@robbiejaeger I'd love to see this as a Yeoman generator.

http://yeoman.io/generators/

**Comment by robbiejaeger** [comment]
@stevekinney  Interesting. I haven't used yeoman before. Would this eliminate the need for students to clone/fork this repo?

**Comment by stevekinney** [comment]
Exactly, it's something we're aiming to do for every project. Students would just be able to do:

```
yo generate game-time
```

And have all the boilerplate ready to go.

**Comment by robbiejaeger** [comment]
Cool. I'll look into it in the coming weeks.

**Comment by nfosterky** [comment]
Issue clean up
